site_name: MadOps Workshop
repo_name: 'workshop'
repo_url: 'https://github.com/madopsio/workshop'
theme:
  name: material
  # palette:
  #   - scheme: default
  #     toggle:
  #       icon: material/weather-sunny
  #       name: Switch to dark mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/weather-night
  #       name: Switch to light mode
#  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.tabs
#    - navigation.tabs.sticky
    - toc.follow
    - navigation.top
plugins:
  - search
nav:
  - Introduction: "index.md"
  - Courses:
    - Ci-Cd: "courses/cicd/cicd.md"
    - Clouds: "courses/clouds/clouds.md"
    - Databases: "courses/databases/databases.md"
    - Networking: "courses/networking/networking.md"
    - Virtualization: "courses/virtualization/virtualization.md"
  - Draft courses:
    - Ci-Cd: "draftcourses/cicd/cicd.md"
    - Clouds: "draftcourses/clouds/clouds.md"
    - Databases: "draftcourses/databases/databases.md"
    - Networking: "draftcourses/networking/networking.md"
    - Virtualization: "draftcourses/virtualization/virtualization.md"
  - Additional materials: "additional-materials/materials.md"